# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  pull_request:
  workflow_dispatch: # allows manual execution of the workflow

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up JDK ${{ vars.JAVA_VERSION }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ vars.JAVA_VERSION }}
          distribution: corretto
          cache: maven

      - name: Install JaCoCo
        run: mvn org.jacoco:jacoco-maven-plugin:prepare-agent

      - name: Compile
        run: mvn -B compile

      - name: Unit Tests with Coverage
        run: mvn -B test jacoco:report

      - name: Check Unit Coverage
        run: |
          COVERAGE=$(cat target/site/jacoco/index.html | grep -oP '(?<=<span class="percentage">)[0-9]+(?=%</span>)')
          if [ "$COVERAGE" -lt 80 ]; then
            echo "Unit Coverage is below 80%. Failing the workflow. Make sure to write tests to cover the code."
            exit 1
          fi

      - name: Package
        run: mvn -B package

      - name: Integration Tests
        run: mvn -B verify jacoco:report

      - name: Check Integration Coverage
        run: |
          COVERAGE=$(cat target/site/jacoco/index.html | grep -oP '(?<=<span class="percentage">)[0-9]+(?=%</span>)')
          if [ "$COVERAGE" -lt 80 ]; then
            echo "Integration Coverage is below 80%. Failing the workflow. Make sure to write tests to cover the code."
            exit 1
          fi

      - name: Install
        run: mvn -B install
